version: '3.7'

services:
  mysql:  
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

  app:
    build: .
    container_name: app
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql

secrets:
  db_root_password:
    file: env/db_pass.env
  db_password:
    file: env/db_pass.env

volumes:
  mysql-data:

networks:
  default: