#!/bin/sh

#below input_file is file ".git/COMMIT_EDITMSG" were commits are stored
INPUT_FILE=$1

#it will copy the commit string from ".git/COMMIT_EDITMSG"
START_LINE=`head -n1 $INPUT_FILE`

#verify commit
if [ -z "${START_LINE}" ];
then

   echo "COMMIT DECRIPTION must not be empty"
   exit 1

else

   # Retrieve information it while committing
   REMOTE_ORIGIN_URL=$(git remote get-url origin)
   REMOTE_ORIGIN_NAME=`basename ${REMOTE_ORIGIN_URL}`
   REMOTE_PATH=$(git rev-parse --show-toplevel)
   REMOTE_PARENT=$(git rev-parse --show-superproject-working-tree)
   BRANCH_NAME=`git branch | awk '/\*/ { print $2; }'`
   AUTHORINFO=$(git var GIT_AUTHOR_IDENT) || exit 1
   NAME=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^\(.*\) <.*$/\1/p')
   EMAIL=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^.* <\(.*\)> .*$/\1/p')

   # path origin
   PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
   cd ${PROJECT}

   # execute command -> docker, save data tracking commit
   docker-compose exec -T app composer commands git:commit-msg "${REMOTE_ORIGIN_NAME}" "${REMOTE_ORIGIN_URL}" "${REMOTE_PATH}" "${REMOTE_PARENT}" "${BRANCH_NAME}" "${START_LINE}" "${NAME}" "${EMAIL}"

fi
